config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "posts#index"
  resources :users, only: [:index, :edit, :show]  #do
  get 'search', to: 'users#search'
  #   collection do
  #     get 'search'
  #   end
  # end
  resources :posts do
    resource :like_posts,only: [:create, :destroy]
    resources :comments, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blood_type.rb
class BloodType < ActiveHash::Base

  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'A型' },
    { id: 3, name: 'B型' },
    { id: 4, name: 'O型' },
    { id: 5, name: 'AB型' }
  ]
  include ActiveHash::Associations
  has_many :users
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user 
end

app/models/like_post.rb
class LikePost < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_uniqueness_of :post_id, scope: :user_id

end

app/models/post.rb
class Post < ApplicationRecord
  validates :text , presence: true
  belongs_to :user
  # has_one_attached :image
  mount_uploader :image, AvatarUploader
  has_many :comments, dependent: :destroy
  has_many :like_posts, dependent: :destroy

  # validates :content, presence: true, unless: :was_attached?

  # def was_attached?
  #   self.image.attached?
  # end

end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '北海道' }, { id: 3, name: '青森県' }, { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' }, { id: 6, name: '秋田県' }, { id: 7, name: '山形県' },
    { id: 8, name: '福島県' }, { id: 9, name: '茨城県' }, { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' }, { id: 12, name: '埼玉県' }, { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' }, { id: 15, name: '神奈川県' }, { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' }, { id: 18, name: '石川県' }, { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' }, { id: 21, name: '長野県' }, { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' }, { id: 24, name: '愛知県' }, { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' }, { id: 27, name: '京都府' }, { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' }, { id: 30, name: '奈良県' }, { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' }, { id: 33, name: '島根県' }, { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' }, { id: 36, name: '山口県' }, { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' }, { id: 39, name: '愛媛県' }, { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' }, { id: 42, name: '佐賀県' }, { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' }, { id: 45, name: '大分県' }, { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' }, { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/sex.rb
class Sex < ActiveHash::Base

    self.data = [
      { id: 1, name: '--' },
      { id: 2, name: '男性' },
      { id: 3, name: '女性' },
      { id: 4, name: '指定しない' },
    ]
  
    include ActiveHash::Associations
    has_many :users
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # has_one_attached :image
  has_many :posts
  has_many :comments
  has_many :like_posts, dependent: :destroy
  mount_uploader :avatar, AvatarUploader

  with_options presence: true do
    validates :nickname
    validates :birth_day 
  end

  with_options numericality: { other_than: 1 } do
    validates :veg_id
    validates :vatch_id
    validates :sex_id
    validates :blood_type_id
    validates :prefecture_id
  end

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :veg
  belongs_to :vatch
  belongs_to :sex
  belongs_to :blood_type
  belongs_to :prefecture

  def already_liked?(post)
    self.like_posts.exists?(post_id: post.id)
  end

end

app/models/vatch.rb
class Vatch < ActiveHash::Base

  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'Rainbow Vatch' },
    { id: 3, name: 'Gold Vatch' },
    { id: 4, name: 'Silver Vatch' },
    { id: 5, name: 'Bronze Vantch' },
    { id: 6, name: 'Green Vantch' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/veg.rb
class Veg < ActiveHash::Base

  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'ヴィーガン(完全菜食)' },
    { id: 3, name: 'ラクト・ベジタリアン(乳菜食)' },
    { id: 4, name: 'ラクト・オボ・ベジタリアン(乳卵菜食)' },
    { id: 5, name: 'ペスコ・ベジタリアン(魚乳卵菜食)' },
    { id: 6, name: 'ポーヨー・ベジタリアン(鳥魚乳卵菜食)' },
    { id: 7, name: 'これからベジタリアンに挑戦' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :profile, :veg_id, :vatch_id, :sex_id, :blood_type_id, :prefecture_id, :birth_day, :avatar,:avatar_cache, :remove_avatar ])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    Comment.create(comment_params)
    redirect_back(fallback_location: root_path)
  end

  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, post_id: params[:post_id])
  end
end

app/controllers/like_posts_controller.rb
class LikePostsController < ApplicationController
   before_action :post_params

  def create
   @like_post = current_user.like_posts.create(post_id: params[:post_id])
  end

  def destroy
    @like_post = current_user.like_posts.find_by(post_id: @post.id)
    @like_post.destroy
  end

   def post_params
     @post = Post.find(params[:post_id])
   end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.includes(:user).order("created_at DESC")
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_create)
 end

 def show
  @post = Post.find(params[:id])
  @comment = Comment.new
  @comments = @post.comments.includes(:user)
end

 private
 def post_create
  params.require(:post).permit(:text,:image).merge(user_id: current_user.id)
 end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_search, only: [:index, :search]

  def index 
    @users = User.all 
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.id == current_user.id
      @user.update(user_params)
      flash[:success] = "プロフィールが更新されました！"
      redirect_to user_path(@user)
    else
      render 'edit'
    end
  end

   def search
     @users = @q.result(distinct: true)
    #  render /users
     # render json: { users: users }
   end

  private

  def user_params
    params.require(:user).permit(:nickname, :profile, :email, :veg_id, :vatch_id, :sex_id, :blood_type_id, :prefecture_id, :birth_day, :avater)
  end 

  def user_search
    @q = User.ransack(params[:q])  # 検索オブジェクトを生成
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/like_posts_helper.rb
module LikePostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def veg_choice(user)
    html = ''
     case user.veg_id 
       when 2 
        html += image_tag('vegan.png')
       when 3 
        html += image_tag('lacto.png') 
       when 4 
        html += image_tag('lacto_ovo.png') 
       when 5 
        html +=  image_tag('pesco.png') 
       when 6 
        html += image_tag('pollo.png') 
       when 7 
        html += image_tag('from_now_on.png') 
       end 
       return raw(html)
  end


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vatch</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
    <script src="https://kit.fontawesome.com/9061779003.js" crossorigin="anonymous"></script>
  　<meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-eval': false %>
  </head>

  <body>
    <header class="header">
    <div class="heater_icon">
      <div class="header__bar row">
        <h1 class="grid-6"><a href="/">Vatch</a></h1>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
          <span><%= image_tag 'menu_green.png' %>
            <ul class="user__info">
              <li>
                <%= link_to "マイページ", "/users/#{current_user.id}" %>
                <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
              </li>
            </ul>
          </span>
        </div>
        <% else %>
          <div class="user_nav grid-6">
          <span><%= image_tag 'menu_green.png' %>
            <ul class="user__info">
              <li>
               <%= link_to "ログイン", new_user_session_path %>
               <%= link_to "新規登録", new_user_registration_path %>
              </li>
            </ul>
          </span>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
        <footer class="footer">
        <div class="footer_icon">
      <%= link_to(posts_path) do %>
       <span><%= image_tag 'home_green.png' %></span>
       <% end %>
      <%= link_to(users_path) do %>
       <span><%= image_tag 'search_green.png' %></span>
       <% end %>
       <span><%= image_tag 'community_green.png' %></span>
       <span><%= image_tag 'bell_green.png' %></span>
       <span><%= image_tag 'message_green.png' %></span>
       </div>
    </footer>
  </body>
</html>

app/views/like_posts/create.js.erb
<%# document.getElementById('posts-contents').innerHTML = '<%= escape_javascript(render @post) ' %>
$('#post_<%= @post.id %>').html("<%= j(render @post) %>" );

app/views/like_posts/destroy.js.erb
document.getElementById("post_<%= @post.id %>").innerHTML = '<%= j(render @post) %>'

app/views/posts/_comment.html.erb
<div class="post">
  <div class="post-left">
    <div class="post-circle-avatar">
      <%=image_tag  comment.user.avatar.to_s %>
    </div>
  </div>
  <div class="post-right">
    <p><%= comment.text %></p>


  </div>
</div>

app/views/posts/_form.html.erb
<%= form_with(model: @post, local: true) do |form| %>
  <%= form.text_area :text, placeholder: "text", cols: "200", rows: "10" %>
  <div class="form-input">

    <label class="form-image">
      <span class="image-file">画像</span>
      <%= form.file_field :image, class: 'hidden' %>
    </label>
  </div>
  <%= form.submit "SEND" %>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <div class="post-left">
    <div class="post-circle-avatar">
      <%=image_tag  post.user.avatar.to_s %>
    </div>
  </div>
  <div class="post-right">
          <p><b><%= post.user.nickname %></b></p>
    <p><%= post.text %></p>
      <% if post.image.present? %>
        <%= image_tag post.image.to_s, class: 'message-image' %>
      <% end %>
    <%= link_to post_path(post) do %>
      <i class="far fa-comment"></i>
    <% end %>
    <%= post.comments.count %>
      <% if user_signed_in? %>
        <% if current_user.already_liked?(post) %>
          <%= link_to post_like_posts_path(post), method: :delete, remote: true do %>
            <i class="fas fa-heart"></i>
          <% end %>
        <% else %>
          <%= link_to post_like_posts_path(post), method: :post, remote: true do %>
            <i class="far fa-heart"></i>
          <% end %>
        <% end %>
      <% else %>
        <%= link_to ""  do %>
          <i class="far fa-heart"></i>
        <% end %>
      <% end %>
    <%= post.like_posts.count %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="user-index">

  <div class="contents row" id='posts-contents'>
    <% @posts.each do |post| %>
      <tr id="post_<%= post.id %>">
        <%= render partial: "post", locals: { post: post } %>
      </tr>
    <% end %>
  </div>

  <%= link_to(new_post_path, class: 'post-btn') do %>
    <span><%= image_tag 'post.png', class: "post-btn-icon" %></span>
  <% end %>

</div>

app/views/posts/new.html.erb
<div class="contents row">
  <div class="container">
    <h3>投稿する</h3>      
    <%= render partial: "form", locals: { post: @post } %>
  </div>
</div>

app/views/posts/show.html.erb
   <div class="contents row">
      <%= render partial: "post", locals: { post: @post } %>
  </div>
 
 <div class="contents row">
  <div class="container">
      <%= form_with(model: [@post, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "コメントする", rows: "2" %>
        <%= form.submit "SEND" %>
      <% end %>
  </div>
</div>
 
 <div class="comments">
      <% if @comments %>
        <% @comments.each do |comment| %>
      <%= render partial: "comment", locals: { comment: comment } %>
      <% end %>
      <% end %>
    </div>

app/views/users/_user.html.erb
<div class="one-user">
   <%# <span class="vatch"><%= image_tag 'gold.png' %></span> 
   <div class="circle-avatar">
      <%=image_tag  user.avatar.to_s %>
    </div>
    <span class="veg"><%= veg_choice(user) %></span>
</div>

app/views/users/index.html.erb
  <div class="search_form" >

  <%= search_form_for @q, url: search_path, id: 'users-search-form', remote: true do |f| %>
  <%= f.label :nickname, "Keyword" %>
  <%= f.search_field :nickname_cont %>
    <%= f.collection_select :prefecture_id_eq, Prefecture.all, :id, :name, {}, include_blank: '指定なし'%>
<%= f.check_box :sex_id_eq , {multiple: true, id: "male"}, checked_value = "2", false %><label for="male" class="label">男性 </label>
<%= f.check_box :sex_id_eq , {multiple: true, id: "female"}, checked_value = "3", false %><label for="female" class="label">女性 </label>

  <%# <%= f.radio_button :sex_id_eq, 3 %>


  <%= f.submit "送信"  %>



<% end %>
<div class="user-index" id="users-index">
  <% @users.each do |user| %>
    <%= render partial: "user", locals: { user: user } %>
  <% end %>
</div>
</div>

app/views/users/search.js.erb
$('#users-index').html("<%= escape_javascript(render partial: "user", collection: @users) %>", );

app/views/users/show.html.erb
<%= form_with(model: @user, local: true) do |f| %>
  <div class="circle-avatar">
    <% if current_user.persisted? && current_user.avatar? %>
      <%= image_tag current_user.avatar.to_s %>
      <label><%= f.check_box :remove_avatar %> 画像を削除</label>
    <% else %>
      <%= image_tag 'user_green.png' %>
      <%= f.hidden_field :avatar_cache %>
    <% end %>
      <%= f.file_field :avatar %>
  </div>
      <%= link_to '編集', edit_user_registration_path(@user.id), method: :get %>
<% end %>